AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  GetFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: handler.getItems
      Runtime: nodejs6.10
      Timeout: 10
      MemorySize: 128
      CodeUri: ./
      Policies: AmazonDynamoDBReadOnlyAccess
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /items
            Method: get
  SaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.saveItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      MemorySize: 128
      CodeUri: ./
      Events:
        PutItems:
          Type: Api
          Properties:
            Path: /items
            Method: put
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.deleteItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      MemorySize: 128
      CodeUri: ./
      Events:
        DeleteItems:
          Type: Api
          Properties:
            Path: /items/{uid}
            Method: delete
  Item:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: uid
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
