AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  GetItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.getItems
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: ./
      Events:
        GetItems:
          Type: Api
          Properties:
            Path: /items/
            Method: get
  SaveItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.saveItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: ./
      Events:
        PutItems:
          Type: Api
          Properties:
            Path: /items/
            Method: put
  DeleteItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.deleteItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      CodeUri: ./
      Events:
        DeleteItems:
          Type: Api
          Properties:
            Path: /items/{uid}
            Method: delete
  Item:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey: uid
      Type: String
    ProvisionedThroughput:
      ReadCapacityUnits: 1
      WriteCapacityUnits: 1
