AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  BucketName:
    Type: String
  CodeKey:
    Type: String
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    StageName: Prod
    Properties:
      DefinitionUri: !Sub "s3://${BucketName}/${CodeKey}/swagger.yml"
  VersionGetFunction:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref GetFunction
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.getItems
      Runtime: nodejs6.10
      Timeout: 10
      MemorySize: 128
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Policies: AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          TABLE_NAME: !Ref item
      Events:
        GetItems:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /items
            Method: get
  VersionSaveFunction:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref SaveFunction
  SaveFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.saveItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref item
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Events:
        PutItems:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /items
            Method: put
  VersionDeleteFunction:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref DeleteFunction
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.deleteItem
      Runtime: nodejs6.10
      Policies: AmazonDynamoDBFullAccess
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !Ref item
      CodeUri:
        Bucket: !Ref BucketName
        Key: !Ref CodeKey
      Events:
        DeleteItems:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /items/{uid}
            Method: delete
  item:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: uid
        Type: String
      ProvisionedThroughput:
         ReadCapacityUnits: 1
         WriteCapacityUnits: 1
